# Xcode

# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Yarn@3
  inputs:
    projectDirectory: ''
    arguments: 'install'
- task: CocoaPods@0
  inputs:
    cwd: 'ios/'
    forceRepoUpdate: true
  displayName: 'pod install using the CocoaPods task with a forced repo update and a custom project directory'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'AwesomeProjectRN'
    sdk: 'iphoneos'
    configuration: 'Debug'
    xcWorkspacePath: 'ios/AwesomeProjectRN.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath